neotracker/neotracker

README.md, packages/neotracker-build/src/entry/server.ts, packages/neotracker-core/src/NEOTracker.ts, packages/neotracker-core/src/bin/neotracker.ts, packages/neotracker-core/src/getConfiguration.ts, packages/neotracker-core/src/index.ts, packages/neotracker-core/src/options/common.ts, packages/neotracker-core/src/options/index.ts, packages/neotracker-core/src/options/main.ts, packages/neotracker-core/src/options/priv.ts, packages/neotracker-core/src/options/test.ts, packages/neotracker-server-db/package.json, packages/neotracker-server-db/src/channels.ts, packages/neotracker-server-db/src/createPubSub.ts, packages/neotracker-server-db/src/db.ts, packages/neotracker-server-scrape-check/package.json, packages/neotracker-server-scrape-check/src/scrapeCheck.ts, packages/neotracker-server-scrape/package.json, packages/neotracker-server-scrape/src/createScraper$.ts, packages/neotracker-server-test/package.json, packages/neotracker-server-web/package.json, packages/neotracker-server-web/src/createServer$.ts, yarn.lock
Moves some code around to allow for a shareable rc configuration function that `@neotracker/core` and `@neotracker/build` can both use. Also updates the configuration template for `db` settings (see README).
Updates `Knex` and `serialize-json` to fix security vulnerabilities.
=> cleanup configuration options with core/build and fix security deps

packages/neotracker-shared-web/src/components/common/logo/Logo.js, packages/neotracker-shared-web/src/components/main/appFooter/AppFooter.js
logo viewbox was too small on loading, fixed it along with bumping our footer date.
=> fix logo clipping on loading

packages/neotracker-server-db/src/createPubSub.ts
pubsub was stalling in production when attempting to run `await currentClient.end()`. Locally this would error out and fail allowing the listener to move on and establish a new connection, however when containerized and run through kubernetes this call would stall and never move passed it.
We fix this by adding a race condition to timeout the attempt if it takes too long.
This could possibly lead to an issue where clients aren't closing properly? But seeing as the issue only comes up on the initial run of the listener it should never be a concern.
=> fix pubsub stall

README.md, packages/neotracker-build/src/entry/server.ts, packages/neotracker-core/src/getConfiguration.ts, packages/neotracker-core/src/options/common.ts, packages/neotracker-server-graphql/src/lib/RootCall.ts, packages/neotracker-server-graphql/src/roots/CurrentPriceRootCall.ts, packages/neotracker-server-graphql/src/roots/PricesRootCall.ts, packages/neotracker-server-web/src/createServer$.ts, packages/neotracker-shared-utils/src/index.ts, packages/neotracker-shared-utils/src/tryParseDateStringToSeconds.ts
CoinMarketCap took their old API offline, which we were using to get current market price and other data for NEO and GAS (GAS is not currently displayed though). CMC requires API users to now signup for their new "pro" API and to use an API key. I signed up and got us an API key we can use for free. Their ping rate limit for the free tier is enough for us to get price data every 5 minutes, instead of the 3 minutes we were previously getting. We think this is fine for now. When we add more price data later we may need/want to upgrade, which will also allow us to hit the endpoint more often.
This also means that anyone running the open-source version of NEO Tracker will need to supply an API key as an environment variable through the RC file, command line, or as a regular NodeJS env …
=> fix(CMC API): fix CoinMarketCap API

packages/neotracker-core/src/options/common.ts, packages/neotracker-server-db/src/loader/createRootLoader$.ts
I really think we shouldn't turn off the cache. But until we figure out the exact problem I think this can turn on the cache for almost all queries, except the ones that aren't working. I think we should try this patch while I dig deeper into what's going on.
Deploy. See if it takes some query load of the PG DB but still updates wallet balances correctly.
=> fix(cache): attempt to add back cache except in coin model

README.md, packages/neotracker-build/src/entry/server.ts, packages/neotracker-core/src/getConfiguration.ts, packages/neotracker-core/src/options/common.ts, packages/neotracker-core/src/options/index.ts, packages/neotracker-core/src/options/main.ts, packages/neotracker-core/src/options/priv.ts, packages/neotracker-core/src/options/test.ts, packages/neotracker-server-db/src/loader/createRootLoader$.ts, packages/neotracker-server-graphql/src/gen/ResolverBuilder.ts, packages/neotracker-server-web/src/middleware/reactApp/index.tsx, packages/neotracker-server-web/src/middleware/reactApp/makeServerHTML.tsx, packages/neotracker-server-web/src/middleware/reactApplication/index.tsx, packages/neotracker-server-web/src/middleware/reactApplication/makeServerHTML.tsx
Adds the ability to add a Google Analytics Tag to NEO Tracker. Just set `googleAnalyticsTag` in the RC file.
Adds back more caching and removes caching just for coin "edges" so that we still take advantage of the cache everywhere except for coin edges.
I tested the Google Analytics Tag locally. It registers the analytics in Google Analytics when passed a tag through the RC file.
I tested the GAS claiming and NEO transfers locally. They work. The same behavior should be observed for other coins, but that should be tested in staging.
#120 
#112
=> fix(cache): remove caching for coin edges, add analytics tag

README.md, packages/neotracker-build/src/HotCompilerServer.ts, packages/neotracker-build/src/develop.ts, packages/neotracker-logger/src/loggers.ts
Logging was out of control. Trying to use `setGlobalLogLevel` didn't work with `yarn develop` because of how `stdout` was handled in `HotCompilerServer.ts`. I replaced `log()` with a new `topLevelLogger`. This is not a *great* solution, but it's much better. You can set `logLevel` on the command line or in the RC file and `yarn develop` will actually see that through.
This does change the format and colors a bit:
Build logs are the same:
But all other logs now have better timestamp formats and slightly better color contrasts:
Try `yarn develop --logLevel silent`. You'll only get the build logs and nothing else.
#124
=> fix(logger): make logging cleaner, more controllable

packages/neotracker-server-db/src/utils/calculateAddressClaimValue.ts
The GAS available to claim is calculated in `neotracker-server-db/src/utils/calculateAddressClaimValue.ts`. This function goes several levels deeper and even uses a `@neo-one/utils` function `calculateClaimAmount`. But part of the input to that was the current block height, which would become out of sync with the actual current block height, causing the problem with the calculated GAS claim value. It appears that when you did claim GAS that the current `maxIndex` block wouldn't change, even though the correct claim transaction was sent to the blockchain. This would cause the apparent discrepancy between the amount that was claimable and the amount that was actually claimed on the blockchain.
To fix this we just reset the `maxIndexFetcher` loader right before we get the max block height …
=> fix(gas): fix gas claiming bug

packages/neotracker-build/src/HotCompilerServer.ts, packages/neotracker-build/src/log.ts, packages/neotracker-logger/package.json, packages/neotracker-logger/src/index.ts, packages/neotracker-logger/src/loggers.ts, packages/neotracker-logger/src/pretty.ts
1. Ditch fancy-log (there is probably an argument here that we could use this for just the compiler logging in `yarn develop` and `yarn build-core`)
2. Set client/web logger default level to 'error'
3. the server will always pickup the logging level we have set and apply it but we need to implement the same functionality for the browser. (not sure where this should be set, somewhere in `@neo-one/client-web` probably)
we should revisit either the fancy-log library for compiler logging, or revisit the pino-pretty default. I was initially opposed to using pino-pretty directly in our code, but having to pipe it in even for a command like `yarn build-core` seems unnecessary. 
Here is example output from `yarn build-core` *without* pino-pretty being piped in:
``` …
```
=> Logging changes to mute browser logs

packages/neotracker-build/src/entry/server.ts, packages/neotracker-core/src/getConfiguration.ts, packages/neotracker-core/src/options/common.ts, packages/neotracker-core/src/options/index.ts, packages/neotracker-core/src/options/main.ts, packages/neotracker-core/src/options/priv.ts, packages/neotracker-core/src/options/test.ts
It appears that it is currently possible to connect to neotracker over HTTP. My suspicion for how HTTPS currently appears to be enforced is via the HSTS header, which we do currently set. See [here](https://helmetjs.github.io/docs/hsts/). Key text:
"The Strict-Transport-Security HTTP header tells browsers to stick with HTTPS and never visit the insecure HTTP version. Once a browser sees this header, it will only visit the site over HTTPS for the next 60 days. **Note that the header won’t tell users on HTTP to switch to HTTPS, it will just tell HTTPS users to stick around. You can enforce HTTPS with the express-enforces-ssl module.**"
Note that we are currently using a copy/pasted version of [this module](https://github.com/shlomisas/koa-sslify/blob/master/index.js) to enforce HTTPS …
=> fix(https): enable HTTPS redirect middleware in prod mode

packages/neotracker-core/src/options/common.ts, packages/neotracker-server-utils-koa/src/middleware/context.ts, packages/neotracker-server-web/src/middleware/enforceHttps.ts
Turns on HTTPS redirect middleware in production, adds HTTP headers logging earlier in middleware, and skips HTTPS redirect middleware if the request is coming from GCP Ingress (assumes all forwarded requests have `X-Forwarded-Proto` header, and health checks do not)
Tested by building new image and deploying to staging cluster. This PR is _slightly_ different from what was tested, so this should still be merged and deployed to staging one last time to confirm.
=> fix(https): update and enable https middleware

packages/neotracker-core/src/options/common.ts
I inadvertently noticed that the browser was blocking `www.google-analytics.com` due to our CSP. I didn't notice this before due to browser extensions I have that blocked it before the CSP could.
Tested locally. It works.
=> fix(csp): minor fix to CSP to allow google-analytics

packages/neotracker-shared-web/src/components/ecosystem/common/EcosystemCard.js
Adds the `rel=noreferrer` and `rel=noopener` to the links on the `Ecosystem` page for security and privacy protections. See [here](https://developers.google.com/web/tools/lighthouse/audits/noopener)
Tested locally.
=> fix(ecosystem): add security/privacy to ecosystem

packages/neotracker-server-graphql/src/live/liveExecuteField.ts
Add logging to help track down issues crashing our web server pods.
Deploy to `prod` and `staging` clusters and wait.
#169
=> fix(logging): add error log to liveExecuteField

packages/neotracker-server-graphql/src/createQueryDeduplicator.ts, packages/neotracker-server-graphql/src/live/LiveServer.ts, root/robots.txt
Adds a strategic log in `createQueryDeduplicator.ts` for when a GQL query execution returns errors. Note that this is not when the document execution _throws_ errors, but when the query itself _returns_ errors. This should add a flood of information in the logs when we get a `graphql_execute_error` response.
This changes the `robots.txt` file to add the `Crawl-delay` directive, which will slow down the requests of most honest web-crawler bots. This may also help mitigate the crashing server pods problem for now.
Deploy to `prod` cluster.
#169
=> fix(logging): add error log to doExecuteForDocument

package.json
We ignore this anyway, so let's remove it so that we don't get used to running `git commit --no-verify`. We need to keep using the other git hooks.
Flow check didn't run when I made this commit.
=> fix(husky): remove FlowJS git hook

packages/neotracker-shared-web/src/components/wallet/new/NewWalletSavePrivateKey.js
In the New Wallet flow there's a page that asked you if you want to print the paper wallet of your new wallet. The button padding is off a bit. This fixes that.
Before:
After:
Tested locally in a variety of viewport sizes. See screenshots.
=> fix(button): small padding nit fix

packages/neotracker-shared-web/src/components/common/logo/Logo.js, packages/neotracker-shared-web/src/components/common/logo/TitleLogo.js
This is a super nit, but if you hover your mouse of the current NEO Tracker logo it will show the title as "Layer 1". I think we want that to show "NEO Tracker Logo". This `title` attribute is primarily for accessibility purposes so that a screen-reader can describe the object to the user. See [here](https://www.sitepoint.com/tips-accessible-svg/). This is why it should be "NEO Tracker Logo" and not just "NEO Tracker".
Tested locally.
=> fix(logo): fix logo title nit

packages/neotracker-core/src/options/index.ts, packages/neotracker-shared-utils/src/types.ts, packages/neotracker-shared-web/src/components/explorer/contract/ContractTable.js
Adds a network config option for a TestNet version of NT.
This includes some blacklisted NEP5 contracts that caused a problem with the scraper due to crazy `precision` attributes, for example `2.2391003503011755e+33`. See logs with the error and my debug log:
This will be tested when deployed to a new `testnet` cluster.
#161
=> feat(testnet): add config option for testnet

packages/neotracker-server-db/src/createPubSub.ts
Reverts #98. We thought that this apparently issue with the NodeJS client library not closing/releasing connections to the DB was causing the problems in #169. When I went to reproduce the issue that #98 supposedly solved I couldn't recreate that issue. So we're reverting #98 here since it's apparently not an issue anymore and with the hope that it solves the problems in #169.
Deployed to local K8s cluster- no problems. Deployed to staging cluster- no problems. Deployed to prod cluster- no problems.
#99 
#169
=> fix(pubsub): remove Promise.race in pubsub

packages/neotracker-core/src/options/common.ts
Not sure why we turned these off in the first place, but they should be enabled.
Watch for problems when we deploy next, but it should be perfectly fine.
=> fix(middleware): enable rateLimit, tooBusy middleware

packages/neotracker-core/src/options/common.ts
Noticed that a script was being blocked in Safari and Firefox while looking at something else. For some reason it's not blocked in Google Chrome, but it should be based on our current CSP. So this just updates the CSP to allow a script to be loaded in Safari and Firefox, possibly other browsers.
=> fix(csp): add google-analytics to script-src

root/robots.txt
Finalizes the work done to fix the crashing web server pods. After reverting the PubSub `Promse.race` everything worked fine for about 24 hours before it appeared that one bot, `MJ12bot` was doing something to still crash the pods repeatedly. This just blocks that one bot, which has been working for several days now without a glitch.
Deployed to prod cluster with no issues.
#169
=> fix(robots): block mj12 crawler

root/robots.txt
This reverts commit af238fdaca3c655acfb0654b4a42b84dabccb422. Apparently trying to block the MegaIndex agent didn't work, so I'm reverting this. I think the problem has to do with resource allocation in Kubernetes.
Already deployed.
#169
=> Revert "fix(robots): block megaindex crawler"

packages/neotracker-server-db/src/models/Coin.ts, packages/neotracker-server-db/src/models/Transfer.ts, packages/neotracker-server-graphql/src/__generated__/schema.graphql, packages/neotracker-server-graphql/src/__generated__/schema.graphql.json, packages/neotracker-shared-utils/src/constants.ts, packages/neotracker-shared-web/src/components/explorer/action/lib/__generated__/TransferItem_transfer.graphql.js, packages/neotracker-shared-web/src/components/explorer/address/__generated__/AddressView_address.graphql.js, packages/neotracker-shared-web/src/components/explorer/address/lib/__generated__/CoinTable_coins.graphql.js, packages/neotracker-shared-web/src/components/explorer/address/lib/__generated__/Coin_coin.graphql.js, packages/neotracker-shared-web/src/components/explorer/address/lib/getSortedCoins.js, packages/neotracker-shared-web/src/components/explorer/asset/lib/AssetNameLinkBase.js, packages/neotracker-shared-web/src/components/explorer/transaction/summary/__generated__/TransactionInvocationSummaryBody_transaction.graphql.js, packages/neotracker-shared-web/src/components/explorer/transfer/__generated__/TransferTable_transfers.graphql.js, packages/neotracker-shared-web/src/components/faq/GeneralFAQView.js, packages/neotracker-shared-web/src/components/wallet/account/__generated__/SendTransaction_address.graphql.js, packages/neotracker-shared-web/src/pages/__generated__/AddressSearchQuery.graphql.js
Temporarily fixes the RPX token issue. It looks like this issue isn't actually as bad as we assumed. It doesn't seem that it's an issue with contract storage, but probably an issue with the token migration. I say this because it looks like we still have correct balances and such with the RPX token, it's just that the token is missing ID and Symbol information in the DB.
So to fix this I basically turned off the associated `required` fields in the GQL server. So when GQL sees that it's gotten a mismatched type from the PG DB it won't freak out. BUT this means that it will be returning an unexpected value: `null` to the front-end. So you see I've handled that by basically using a default value anywhere that we try to use `coin.asset` (only two places).
I left a comment in the two `required: …
=> fix(rpx): temporary fix for RPX token bug

packages/neotracker-server-db/package.json, packages/neotracker-server-scrape-check/package.json, packages/neotracker-server-scrape/package.json, packages/neotracker-server-test/package.json
Pin `knex` dependency to make NEO Tracker work in NEO•ONE repo.
Published alpha version of NT, then used in NEO•ONE.
=> fix(knex): pin knex dependency for neo-one

scripts/Dockerfile
Same as title. This is not necessarily a permanent fix if there's a memory leak though. Time will give us more info.
Deployed to prod cluster and no pod restarts in 24 hours.
#225
=> fix(memory): increase nodejs max memory in docker image

packages/neotracker-build/src/entry/server.ts, packages/neotracker-server-scrape/src/MigrationHandler.ts, packages/neotracker-server-scrape/src/createScraper$.ts, packages/neotracker-server-scrape/src/migrations/index.ts, packages/neotracker-shared-web/src/components/exchange/common/PoweredByMoonPay.js
-Adds to the `Migrations` array some logic for the LONG and RPX tokens so that they still exist in the Asset table of the NT database, and thus will still show up in NT. This is a sort of manual intervention into the scraper and the NT database. I also added and edited logic for when/how the scraper will execute the migration function logic on startup.
-Added a line to the BuyNEO page to contact us via Twitter/FB if a user has issues.
-Fixed how the `yarn develop` command reads/sets the `nodeRpcUrl`/`rpcURL` option.
Ran a local NEO•ONE node, local PG database, and ran the scraper. RPX and LONG now show up appropriately in NT when run locally. This DB will be pushed to our cloud infra.
#234
=> fix(tokens): fix broken LONG and RPX tokens with migrations

packages/neotracker-server-web/package.json, yarn.lock
Update `serialize-javascript` dep for security reasons.
Ran locally. Seems to work.
=> fix(dep): update serialize-javascript dependency

packages/neotracker-server-scrape/src/createScraper$.ts, packages/neotracker-server-scrape/src/migrations/index.ts
Add migration network to migrations so that we don't inadvertently do migrations in TestNet that should only be done with MainNet, and vice-versa.
No test needed. Going to deploy.
=> fix(migration): change migrations to account for network

packages/neotracker-server-graphql/package.json, packages/neotracker-server-graphql/src/roots/MoonPayRootCall.ts
Add cache to MoonPay GQL response returns faster when trying to hash the same value.
Ran locally and it seems to work.
This could *potentially* help fix the memory leak issue.
#225
=> feat(cache): add cache for moonpay hash

packages/neotracker-server-graphql/src/roots/MoonPayRootCall.ts
Increases the size of the cache used for the MoonPay hashing function. The `LRUCache` is sized by number of items in the cache. Each item consists of a key and a value, both of which are strings. The key is the URL string, which is let's say about 100 characters. And the value is the SHA256 hash of the URL, which always comes out to a length of 44 characters. In JS each character should be 2 bytes. So each item will take up about 300 bytes (rounding up). So with the original size of 100 the cache would only take up about 30KB. Now, with a cache of 10,000 the cache should take up about 3MB. This will allow NT to handle more traffic as the hashing won't consume as much memory for each concurrent user session.
This is a temporary solution to this hash function crashing our web pods. The real …
=> feat(cache): increase moonpay hash cache

scripts/Dockerfile
It appears that setting `--max-old-space-size` here doesn't seem to make it into the container's node process. But setting it as an environment variable in the k8s config does. And it's easier to edit the memory size there.
Tested by deploying to production and looking at logs.
#225
=> fix(memory): remove memory size from Dockerfile. put in k8s config
