neotracker/neotracker

actions/dockerhub/Dockerfile
actions/dockerhub/entrypoint.sh

other half of the actions that need to be added to keep the `neotracker/core` image up to date.

add the actions commands to run

---

packages/neotracker-shared-web/src/components/common/view/CommonHeader.js
packages/neotracker-shared-web/src/components/common/view/PageViewHeader.js
packages/neotracker-shared-web/src/components/wallet/account/ClaimGASStep.js
packages/neotracker-shared-web/src/components/wallet/paper/PaperWalletLabeled.js
packages/neotracker-shared-web/src/lib/link/Link.js
packages/neotracker-shared-web/src/lib/markdown/Markdown.js
scripts/Dockerfile

fix github actions image

---

packages/neotracker-shared-web/src/components/ecosystem/main/cards.js

NEO refers to the token, while Neo refers to the entire Neo project.

fix(nit): NEO to Neo

---

packages/neotracker-core/src/options/common.ts
scripts/Dockerfile

fix docker image to copy yarn.lock/ also fix rpcUrl in common settings

---

packages/neotracker-shared-web/src/components/wallet/account/SendTransaction.js

fix(bug): fix type import bug and rpcUrl config

---

packages/neotracker-shared-web/src/components/wallet/account/SendTransactionDialog.js

Fix spacing for transaction confirmation dialog.

fix(spacing): fix typography nit

---

packages/neotracker-core/src/options/common.ts

Fix some configuration options to make NEO Tracker work.

fix(rootloader): turn off server rootLoader cache

---

packages/neotracker-shared-web/src/components/exchange/common/BuyNEOCard.js

Fix a tiny spacing/alignment issue in the MoonPay swap card.
Looks good:
#78

fix(moonpay): fix spacing nit

---

packages/neotracker-server-graphql/src/createQueryDeduplicator.ts
root/robots.txt

Cleans up logging and reverts change to `robots.txt`.
#169

fix(logging): cleanup logging and revert robots.txt

---

packages/neotracker-shared-web/src/App.js
packages/neotracker-shared-web/src/components/faq/GeneralFAQView.js
packages/neotracker-shared-web/src/components/faq/index.js
packages/neotracker-shared-web/src/components/main/appBar/AppBarDownMD.js
packages/neotracker-shared-web/src/components/main/appBar/AppBarUpMD.js
packages/neotracker-shared-web/src/components/wallet/faq/WalletFAQView.js
packages/neotracker-shared-web/src/pages/FAQ.js
packages/neotracker-shared-web/src/routes.js

Adds an FAQ page to NEO Tracker with general FAQ questions.
Deployed to `staging`. Go there and test it out.
#82

feat(faq): add new general faq page

---

.size-limit.js
package.json
packages/neotracker-build/src/entry/graphql.ts
packages/neotracker-client-web-next/package.json
packages/neotracker-client-web/package.json
packages/neotracker-server-db/package.json
packages/neotracker-server-graphql/package.json
packages/neotracker-server-scrape-check/package.json
packages/neotracker-server-scrape/package.json
packages/neotracker-server-scrape/src/db/BlockUpdater.ts
packages/neotracker-server-utils-koa/package.json
packages/neotracker-server-utils/package.json
packages/neotracker-server-web/package.json
packages/neotracker-shared-graphql/package.json
packages/neotracker-shared-web-next/package.json
packages/neotracker-shared-web/package.json
yarn.lock

title, updates should stop any opencensus leaks that were happening previously.

upgrade neo-one dependencies

---

packages/neotracker-shared-web/src/components/faq/GeneralFAQView.js

Makes the FAQ more accurate when it comes to problems and solutions for transactions not going through.

fix(faq): update faq related to transaction fees

---

scripts/DockerfileTemp

Add a new Dockerfile for use in quick, local development.
Didn't test.

feat(docker): new dockerfile for local development use

---

root/robots.txt

Block the MegaIndex web crawler. I don't know what it's doing differently than other crawlers but it seems to be causing serious problems, above and beyond whatever problem the other crawlers are causing. So I think we should block it for now.
#169

fix(robots): block megaindex crawler

---

root/robots.txt

Pods no longer crashing so let's unblock this bot.

fix(robots): unblock mjbot

---

packages/neotracker-shared-web/src/components/exchange/common/BuyNEOCard.js

Allows the MoonPay iframe to show our users popups, which is necessary for the iframe's functionality.
Deployed and tested manually.

fix(moonpay): fix iframe sandbox

---

packages/neotracker-core/package.json

Just bumps the neotracker/core version for release.

chore(release): bump neotracker core version for release

---

packages/neotracker-core/src/options/common.ts
packages/neotracker-core/src/options/index.ts

Only final testing revealed that we needed to add another MoonPay URL to the CSP. This does that and cleans up the MoonPay URLs with variables.
This is deployed to prod but still needs to be hand tested.

fix(moonpay): fix csp for moonpay api url

---

packages/neotracker-build/src/entry/build.ts

Updates node engine version for release.

fix(node): update node engine version

---

packages/neotracker-core/src/options/common.ts

fix(csp): add more moonpay urls

---

packages/neotracker-core/src/options/common.ts

fix(csp): minor edits for safari

---

packages/neotracker-core/src/options/common.ts

Adds another URL to CSP and fixes spelling error.

fix(moonpay): fix moonpay corner cases csp

---

packages/neotracker-core/src/options/common.ts

Essentially removes frame-src for CSP to allow MoonPay frame to do it's thing.
Tested on TestNet and bought BCH successfully.

fix(csp): minor edits for moonpay

---

packages/neotracker-build/package.json
packages/neotracker-core/package.json
packages/neotracker-server-test/package.json
yarn.lock

Update `sqlite3` dependency to support NodeJS v12.x.

fix(sqlite): update sqlite3 dependency for NodeJSv12 support

---

packages/neotracker-core/package.json

Update version before publishing.

fix(version): update version number

---

packages/neotracker-server-graphql/src/roots/MoonPayRootCall.ts

Nits to MoonPayRootCall and also trying to fix potential memory leaks.
#225

fix(moonpay): try to fix memory leak

---

README.md

Fix some nits I noticed in the README.
None.
None.

fix(readme): fix nits

---

packages/neotracker-shared-web/src/components/exchange/common/PoweredByMoonPay.js

fix(typo): fix moonpay typo

---

packages/neotracker-server-db/src/lib/Base.ts

title, another attempt at fixing our memory leak.

add 'useLimitInFirst' property to models for object memory leak
